### ISSUE TITLE
Update CKAN Version.

### ISSUE THREAD

**Issue by Ruedii** [linuxgurugamer/EVAHandrailsPack#2]
Just the usual low priority note that the CKAN and Version Checker info need to be updated again.  If I had permission to set priority on filing a bug report, I would have set it to the lowest option. 

Might be a good idea to move this to spare parts so it can receive this patch in bulk with the other spare parts mods.  It seems to fit the scope of Spare parts as perfect as you could ask for.

**Comment by linuxgurugamer** [comment]
What needs to be updated?  
The avc file is correct, it specifies a min version.

**Comment by Ruedii** [comment]
CKAN is not, listing it as 1.5.1.  Considering the rare chance that this mod would break.  It might be best to change CKAN to only specify minimum version as well. 

These things happen.  BTW, I think these things would happen less if more mods were pulled into the Spare Parts maintenance pack tree.


As of my assessment on the possible future incompatabilities, I'd estimate the chance of <0.1%, and that's a generous estimate.

Here is it as follows:
Rare occasions happen that all ladder parts closer than a certain point are subject to random"collision Krackens" flinging kerbals due to adjustments on the surface collider distance.  This mod has never seen this bug despite it even hitting stock parts on several occasions.  These ladder parts have the furthest handholds in standard of any ladder part I've seen.   They are safe beyond safe from that, although some crafts using them may run into issues with this as some people might abuse this by installing science instruments and other stuff under them using that clearance.   I think it is safe so long as the ladder module is not completely deprecated for a new one.  

Considering the simplicity of the ladder module I doubt there will be one like the wheel module fiasco.

**Comment by linuxgurugamer** [comment]
Oh, that's because of my build process and where CKAN is pulling it's information.  I'll fix that today

**Comment by linuxgurugamer** [comment]
Updated, CKAN should see the update in the next few hours

**Comment by Ruedii** [comment]
You should make a script to do this across all your mods easily in the future.
